# Generated by Django 4.2.7 on 2024-07-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100)),
                ('date1', models.DateField()),
                ('activity1', models.CharField(max_length=500)),
                ('duration1', models.IntegerField()),
            ],
        ),
    ]
